# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly" # Check for updates to GitHub Actions every week

  ################
  #   INTERNAL   #
  ################
  - package-ecosystem: "gomod"
    directory: "/internal/awsxray"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/internal/awsxray/testdata/sampleapp"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/internal/awsxray/testdata/sampleserver"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/internal/common"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/internal/k8sconfig"
    schedule:
      interval: "weekly"

  ##################
  #   EXTENSIONS   #
  ##################
  - package-ecosystem: "gomod"
    directory: "/extension/jmxmetricsextension"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/extension/httpforwarder"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/extension/observer"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/extension/observer/hostobserver"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/extension/observer/k8sobserver"
    schedule:
      interval: "weekly"

  #################
  #   EXPORTERS   #
  #################
  - package-ecosystem: "gomod"
    directory: "/exporter/alibabacloudlogserviceexporter"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/exporter/awsemfexporter"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/exporter/awsxrayexporter"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/exporter/azuremonitorexporter"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/exporter/carbonexporter"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/exporter/datadogexporter"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/exporter/elasticexporter"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/exporter/honeycombexporter"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/exporter/jaegerthrifthttpexporter"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/exporter/kinesisexporter"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/exporter/logzioexporter"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/exporter/newrelicexporter"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/exporter/sapmexporter"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/exporter/sentryexporter"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/exporter/signalfxexporter"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/exporter/splunkhecexporter"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/exporter/stackdriverexporter"
    schedule:
      interval: "weekly"

  ##################
  #   PROCESSORS   #
  ##################
  - package-ecosystem: "gomod"
    directory: "/processor/groupbytraceprocessor"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/processor/k8sprocessor"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/processor/metricstransformprocessor"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/processor/resourcedetectionprocessor"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/processor/routingprocessor"
    schedule:
      interval: "weekly"

  #################
  #   RECEIVERS   #
  #################
  - package-ecosystem: "gomod"
    directory: "/receiver/awsecscontainermetricsreceiver"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/receiver/awsxrayreceiver"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/receiver/carbonreceiver"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/receiver/collectdreceiver"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/receiver/dockerstatsreceiver"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/receiver/k8sclusterreceiver"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/receiver/kubeletstatsreceiver"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/receiver/prometheusexecreceiver"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/receiver/receivercreator"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/receiver/redisreceiver"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/receiver/sapmreceiver"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/receiver/signalfxreceiver"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/receiver/simpleprometheusreceiver"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/receiver/splunkhecreceiver"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/receiver/stanzareceiver"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/receiver/statsdreceiver"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/receiver/wavefrontreceiver"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/receiver/windowsperfcountersreceiver"
    schedule:
      interval: "weekly"

  ###############
  #   TESTBED   #
  ###############
  - package-ecosystem: "gomod"
    directory: "/testbed"
    schedule:
      interval: "weekly"

  ################
  #   TRACEGEN   #
  ################
  - package-ecosystem: "gomod"
    directory: "/tracegen"
    schedule:
      interval: "weekly"
